--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria (
    categoria_id integer NOT NULL,
    descripcion character varying(255),
    nombre_categoria character varying(100) NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: categoria_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria ALTER COLUMN categoria_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comentario (
    comentario_id integer NOT NULL,
    probabilidad double precision NOT NULL,
    sentimiento character varying(255) NOT NULL,
    texto text NOT NULL,
    sesion_id integer NOT NULL
);


--
-- Name: comentario_comentario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comentario ALTER COLUMN comentario_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentario_comentario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.producto (
    producto_id integer NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    negativos integer NOT NULL,
    neutrales integer NOT NULL,
    nombre_producto character varying(200) NOT NULL,
    positivos integer NOT NULL,
    total_menciones integer NOT NULL,
    ultima_actualizacion timestamp(6) without time zone,
    categoria_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: producto_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.producto ALTER COLUMN producto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol (
    rol_id integer NOT NULL,
    nombre_rol character varying(255)
);


--
-- Name: rol_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rol ALTER COLUMN rol_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesion (
    sesion_id integer NOT NULL,
    avg_score double precision NOT NULL,
    fecha timestamp without time zone NOT NULL,
    negativos integer NOT NULL,
    neutrales integer NOT NULL,
    positivos integer NOT NULL,
    total integer NOT NULL,
    producto_id integer,
    usuario_id integer NOT NULL
);


--
-- Name: sesion_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesion_producto (
    sesion_producto_id integer NOT NULL,
    menciones_sesion integer NOT NULL,
    negativos_sesion integer NOT NULL,
    neutrales_sesion integer NOT NULL,
    positivos_sesion integer NOT NULL,
    producto_id integer NOT NULL,
    sesion_id integer NOT NULL
);


--
-- Name: sesion_producto_sesion_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sesion_producto ALTER COLUMN sesion_producto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sesion_producto_sesion_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesion_sesion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sesion ALTER COLUMN sesion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sesion_sesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_rol (
    user_id integer NOT NULL,
    rol_id integer NOT NULL
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    usuario_id integer NOT NULL,
    apellido character varying(255) NOT NULL,
    "contrase├▒a" character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL
);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN usuario_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (categoria_id);


--
-- Name: comentario comentario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT comentario_pkey PRIMARY KEY (comentario_id);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (producto_id);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (rol_id);


--
-- Name: sesion sesion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion
    ADD CONSTRAINT sesion_pkey PRIMARY KEY (sesion_id);


--
-- Name: sesion_producto sesion_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_producto
    ADD CONSTRAINT sesion_producto_pkey PRIMARY KEY (sesion_producto_id);


--
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (usuario_id);


--
-- Name: user_rol fk307wepnnuevxoycwfym4twbjs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rol
    ADD CONSTRAINT fk307wepnnuevxoycwfym4twbjs FOREIGN KEY (user_id) REFERENCES public.usuarios(usuario_id);


--
-- Name: sesion fk5hupvl2jxbnfvrxhtfay43uaw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion
    ADD CONSTRAINT fk5hupvl2jxbnfvrxhtfay43uaw FOREIGN KEY (usuario_id) REFERENCES public.usuarios(usuario_id);


--
-- Name: producto fk6vj0hd5jtfv3oe5yl4u7mvtqd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk6vj0hd5jtfv3oe5yl4u7mvtqd FOREIGN KEY (usuario_id) REFERENCES public.usuarios(usuario_id);


--
-- Name: categoria fk867hc4nfxbdmssdjato37d3vw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT fk867hc4nfxbdmssdjato37d3vw FOREIGN KEY (usuario_id) REFERENCES public.usuarios(usuario_id);


--
-- Name: sesion fkdw8x8xxbic5682dbpn9y3jle; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion
    ADD CONSTRAINT fkdw8x8xxbic5682dbpn9y3jle FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id);


--
-- Name: sesion_producto fkmvaipp0212a0iwcom97k55sfd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_producto
    ADD CONSTRAINT fkmvaipp0212a0iwcom97k55sfd FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id);


--
-- Name: producto fkodqr7965ok9rwquj1utiamt0m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkodqr7965ok9rwquj1utiamt0m FOREIGN KEY (categoria_id) REFERENCES public.categoria(categoria_id);


--
-- Name: user_rol fkpfraq7jod5w5xd3sxm3m6y1o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rol
    ADD CONSTRAINT fkpfraq7jod5w5xd3sxm3m6y1o FOREIGN KEY (rol_id) REFERENCES public.rol(rol_id);


--
-- Name: sesion_producto fkt834uowiyfh4nmtlhcae2ify2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_producto
    ADD CONSTRAINT fkt834uowiyfh4nmtlhcae2ify2 FOREIGN KEY (sesion_id) REFERENCES public.sesion(sesion_id);


--
-- Name: comentario fktd5txp3wb8d1d5s7tj0akh6nc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT fktd5txp3wb8d1d5s7tj0akh6nc FOREIGN KEY (sesion_id) REFERENCES public.sesion(sesion_id);


--
-- PostgreSQL database dump complete
--

